include theme.conf

# ШРИФТЫ
font_family      JetBrainsMono Nerd Font
bold_font        auto
italic_font      auto
bold_italic_font auto
font_size        12.0

# ОКНО
window_padding_width     15
background_opacity       0.85
hide_window_decorations  yes
confirm_os_window_close  0

# ВКЛАДКИ
tab_bar_edge        top
tab_bar_style       powerline
tab_powerline_style slanted

# КУРСОР
cursor_shape          block
cursor_blink_interval 0.5

# МЫШЬ
url_style       curly
open_url_with   default
copy_on_select  yes

# ЗВУК
enable_audio_bell no

# KEYBINDS
map ctrl+equal change_font_size all +1.0
map ctrl+minus change_font_size all -1.0
map ctrl+0     change_font_size all 0
