# MPV CONFIG

no-border
vo=gpu
gpu-api=vulkan
hwdec=auto-safe

osc=no
osd-bar=no

osd-font='JetBrainsMono Nerd Font'
osd-font-size=32
osd-color='#cdd6f4'
osd-border-color='#1e1e2e'
osd-bar-align-y=0.6
osd-border-size=2
osd-bar-h=2
osd-bar-w=60
